apiVersion: 2022-10-01
kind: ContainerApp
metadata:
  name: ministerioai-platform
spec:
  managedEnvironmentId: /subscriptions/{subscription-id}/resourceGroups/{resource-group}/providers/Microsoft.App/managedEnvironments/{environment-name}
  configuration:
    activeRevisionsMode: Single
    ingress:
      external: true
      targetPort: 5000
      transport: http
      allowInsecure: false
    secrets:
      - name: database-url
        value: "your-postgres-connection-string"
      - name: stripe-secret
        value: "your-stripe-secret-key"
      - name: openai-api-key
        value: "your-openai-api-key"
      - name: session-secret
        value: "your-session-secret"
      - name: sendgrid-api-key
        value: "your-sendgrid-api-key"
    registries:
      - server: {your-acr-name}.azurecr.io
        username: {your-acr-username}
        passwordSecretRef: acr-password
  template:
    containers:
      - name: ministerioai-platform
        image: {your-acr-name}.azurecr.io/ministerioai-platform:latest
        env:
          - name: NODE_ENV
            value: "production"
          - name: PORT
            value: "5000"
          - name: DATABASE_URL
            secretRef: database-url
          - name: STRIPE_SECRET_KEY
            secretRef: stripe-secret
          - name: OPENAI_API_KEY
            secretRef: openai-api-key
          - name: SESSION_SECRET
            secretRef: session-secret
          - name: SENDGRID_API_KEY
            secretRef: sendgrid-api-key
          - name: FROM_EMAIL
            value: "support@ministerioai.com"
        resources:
          cpu: 0.5
          memory: 1Gi
        probes:
          - type: Liveness
            httpGet:
              path: /api/_version
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          - type: Readiness
            httpGet:
              path: /api/_version
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
    scale:
      minReplicas: 1
      maxReplicas: 10
      rules:
        - name: http-scaling
          http:
            metadata:
              concurrentRequests: "100"